Repository Reem-lab/space-travelers-hub, pull requests merged in 2022-03, with the labels that each got.

#26 Feature/setup react
  .babelrc
  .eslintrc.json
  .github/workflows/linters.yml
  .gitignore
  .stylelintrc.json
  README.md
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/assets/images/planet.png
  src/components/Dragons.js
  src/components/Missions.js
  src/components/MyProfile.js
  src/components/NavBar.js
  src/components/Rockets.js
  src/index.js
  src/redux/store.js
  src/style/App.css
  src/style/MyProfile.css
  src/style/NavBar.css
  src/style/index.css
  src/tests/App.test.js
  yarn.lock
Labels: enhancement

#28 Feature/dragons/fetch data
  package-lock.json
  package.json
  src/components/Dragons.js
  yarn.lock
Labels: good first issue

#29 Feature/dragons/structure component
  package-lock.json
  package.json
  src/components/Dragon.js
  src/components/Dragons.js
  src/index.js
  yarn.lock
Labels: enhancement

#37 Feature/dragons/booking
  src/components/Dragon.js
  src/components/Dragons.js
  src/components/MyProfile.js
  src/redux/actions/dragonsActions.js
  src/redux/reducers/dragonsReducer.js
  src/style/App.css
Labels: enhancement

#48 Bugfix/dragons/dispatch render
  src/__tests__/App.test.js
  src/__tests__/Dragon.test.js
  src/__tests__/Mission.test.js
  src/__tests__/__snapshots__/App.test.js.snap
  src/__tests__/__snapshots__/Dragon.test.js.snap
  src/components/Dragon.js
  src/components/Dragons.js
  src/components/Mission.js
  src/components/MyProfile.js
  src/redux/actions/dragonsActions.js
  yarn.lock
Labels: bug

#42 Implementation of Space Traveller's Hub Project
  .babelrc
  .eslintrc.json
  .github/workflows/linters.yml
  .gitignore
  .stylelintrc.json
  README.md
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/__tests__/App.test.js
  src/__tests__/Dragon.test.js
  src/__tests__/Mission.test.js
  src/__tests__/NavBar.test.js
  src/__tests__/Rockets.test.js
  src/__tests__/__snapshots__/App.test.js.snap
  src/__tests__/__snapshots__/Dragon.test.js.snap
  src/__tests__/__snapshots__/NavBar.test.js.snap
  src/__tests__/__snapshots__/Rockets.test.js.snap
  src/assets/images/app_screenshot.gif
  src/assets/images/planet.png
  src/components/Dragon.js
  src/components/Dragons.js
  src/components/Mission.js
  src/components/Missions.js
  src/components/MyProfile.js
  src/components/NavBar.js
  src/components/Rockets.js
  src/index.js
  src/redux/actions/RocketsActions.js
  src/redux/actions/dragonsActions.js
  src/redux/actions/missionsActions.js
  src/redux/api/missionsAPIHelper.js
  src/redux/reducers/RocketsReducer.js
  src/redux/reducers/dragonsReducer.js
  src/redux/reducers/missionsReducer.js
  src/redux/rootReducer.js
  src/redux/store.js
  src/style/App.css
  src/style/Missions.css
  src/style/MyProfile.css
  src/style/NavBar.css
  src/style/Rockets.css
  src/style/index.css
  src/tests/Mission.test.js
  yarn.lock
Labels: enhancement
